name: "web_demo"
mode: "dev"
port: 8090

start_time : "2021-11-01"
machine_id : 1

log:
  "level": "debug"
  "filename": "web_app.log"
  "max_size": 200
  "max_age": 30
  "max_backup": 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "xlsf0205"
  dbname: "web_app"
  max_open_conn: 200
  max_idle_conn: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100